version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    group_add:
      - 109
    ports:
      - 8096:8096
    volumes:
      - /new-pool/jellyfin/config:/config
      - /new-pool/jellyfin/cache:/cache
      - /new-pool/jellyfin/media:/media
    devices:
      - /dev/dri:/dev/dri # for hardware acceleration
    restart: 'unless-stopped'
